languageCode = "en-us"
title = "Florian Bürger"
baseURL = "https://www.florianbuerger.com/"
author = "Florian Bürger"

footnoteReturnLinkContents = "↩&#xFE0E;"
pluralizelisttitles = "false"

pygmentsstyle = "bw"
pygmentscodefences = true

# SectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false


[[menu.main]]
  name = "Work"
  url  = "/work"
  weight = 1

[[menu.main]]
  name = "Photos"
  url  = "/photos"
  weight = 2

# [[menu.main]]
#   name = "Blog"
#   url  = "/blog"
#   weight = 3
