languageCode = "en-us"
title = "Florian Bürger"
baseURL = "https://www.florianbuerger.com/"
author = "Florian Bürger"

footnoteReturnLinkContents = "↩&#xFE0E;"
pluralizelisttitles = "false"

pygmentsstyle = "bw"
pygmentscodefences = true

# SectionPagesMenu = "main"

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Work"
  url  = "/work"
  weight = 1

[[menu.main]]
  name = "Photos"
  url  = "/photos"
  weight = 2

[[menu.main]]
  name = "Blog"
  url  = "/blog"
  weight = 3
