languageCode = "en-us"
title = "Florian Bürger"
baseURL = "https://www.florianbuerger.com/"
author = "Florian Bürger"

footnoteReturnLinkContents = "↩&#xFE0E;"
pluralizelisttitles = "false"

pygmentsstyle = "bw"
pygmentscodefences = true

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Work"
  url  = "/work"
[[menu.main]]
  name = "Blog"
  url  = "/blog"
