languageCode = "en-us"
title = "Florian Bürger"
baseURL = "https://www.florianbuerger.com/"
author = "Florian Bürger"

footnoteReturnLinkContents = "↩"
pluralizelisttitles = "false"

pygmentsstyle = "bw"
pygmentscodefences = true

[[menu.main]]
    name = "↪ Work"
    url  = "/work"
[[menu.main]]
    name = "↪ Blog"
    url  = "/blog"

